version: '3.6'

services:
  mysql80027:
    container_name: mysql-8.0.27
    image: 'mysql:8.0.27'
    restart: always
    # privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: rtc80027
      MYSQL_USER: rtc
      MYSQL_PASSWORD: rtc123456
    ports:
      - '3327:3306'
    volumes:
      - '/opt/docker/mysql80027:/var/lib/mysql'

  mysql57040:
    container_name: mysql-5.7.40
    image: 'mysql:5.7.40'
    restart: always
    # privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: rtc50040
      MYSQL_USER: rtc
      MYSQL_PASSWORD: rtc123456
    ports:
      - '3340:3306'
    volumes:
      - '/opt/docker/mysql50040:/var/lib/mysql'
